DESCRIPTION_URL_DICTIONARY = {
    'few clouds': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Partly_Cloudy_%2814207954735%29.jpg/480px-Partly_Cloudy_%2814207954735%29.jpg',
     'heavy intensity rain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Heavy_Rain_001.jpg/480px-Heavy_Rain_001.jpg',
     'thunderstorm with rain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Lightning_Pritzerbe_01_%28MK%29.jpg/480px-Lightning_Pritzerbe_01_%28MK%29.jpg',
     'sleet': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Ice_pellets_Tuscany.jpg/480px-Ice_pellets_Tuscany.jpg',
     'light shower sleet': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Ice_pellets_Tuscany.jpg/480px-Ice_pellets_Tuscany.jpg',
     'shower rain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Light_rain_on_a_roof.jpg/480px-Light_rain_on_a_roof.jpg',
     'thunderstorm with light rain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Light_rain_on_a_roof.jpg/480px-Light_rain_on_a_roof.jpg',
     'proximity thunderstorm with drizzle': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Lightning_Pritzerbe_01_%28MK%29.jpg/480px-Lightning_Pritzerbe_01_%28MK%29.jpg',
     'proximity thunderstorm': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Lightning_Pritzerbe_01_%28MK%29.jpg/480px-Lightning_Pritzerbe_01_%28MK%29.jpg',
     'proximity thunderstorm with rain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Lightning_Pritzerbe_01_%28MK%29.jpg/480px-Lightning_Pritzerbe_01_%28MK%29.jpg',
     'light snow': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Snow_flurries_over_the_pond_%283282132489%29.jpg/480px-Snow_flurries_over_the_pond_%283282132489%29.jpg',
     'heavy shower snow': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Heavy_Snow%2C_London_N14_-_geograph.org.uk_-_2200728.jpg/480px-Heavy_Snow%2C_London_N14_-_geograph.org.uk_-_2200728.jpg',
     'heavy intensity drizzle': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Light_rain_on_a_roof.jpg/480px-Light_rain_on_a_roof.jpg',
     'volcanic ash': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Volcanic_Ash_Dunes.jpg/480px-Volcanic_Ash_Dunes.jpg',
     'sky is clear': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Clear_Sky.jpg/480px-Clear_Sky.jpg',
     'overcast clouds': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Cloudy_.jpg/480px-Cloudy_.jpg',
     'sand': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Car_parking_at_dust_storm_%28Malinovskogo%2C_Rostov%29.jpg/480px-Car_parking_at_dust_storm_%28Malinovskogo%2C_Rostov%29.jpg',
     'squalls': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Squall_Over_Vila_Bay_%28Imagicity_73%29.jpg/480px-Squall_Over_Vila_Bay_%28Imagicity_73%29.jpg',
     'light rain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Light_rain_on_a_roof.jpg/480px-Light_rain_on_a_roof.jpg',
     'proximity moderate rain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Rain_shower_after_cold_front_3.JPG/480px-Rain_shower_after_cold_front_3.JPG',
     'sand/dust whirls': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Dust_devil.jpg/480px-Dust_devil.jpg',
     'thunderstorm with heavy drizzle': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Lightning_Pritzerbe_01_%28MK%29.jpg/480px-Lightning_Pritzerbe_01_%28MK%29.jpg',
     'thunderstorm with heavy rain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Lightning_Pritzerbe_01_%28MK%29.jpg/480px-Lightning_Pritzerbe_01_%28MK%29.jpg',
     'shower drizzle': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Light_rain_on_a_roof.jpg/480px-Light_rain_on_a_roof.jpg',
     'light intensity shower rain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Light_rain_on_a_roof.jpg/480px-Light_rain_on_a_roof.jpg',
     'light rain and snow': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Heavy_Rain_-_panoramio.jpg/480px-eavy_Rain_-_panoramio.jpg',
     'light shower snow': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Snow_flurries_over_the_pond_%283282132489%29.jpg/480px-Snow_flurries_over_the_pond_%283282132489%29.jpg',
     'drizzle': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Light_rain_on_a_roof.jpg/480px-Light_rain_on_a_roof.jpg',
     'freezing rain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Heavy_Rain_-_panoramio.jpg/480px-eavy_Rain_-_panoramio.jpg',
     'very heavy rain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Heavy_Rain_001.jpg/480px-Heavy_Rain_001.jpg',
     'shower snow': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Heavy_Snow%2C_London_N14_-_geograph.org.uk_-_2200728.jpg/480px-Heavy_Snow%2C_London_N14_-_geograph.org.uk_-_2200728.jpg',
     'heavy thunderstorm': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Lightning_Pritzerbe_01_%28MK%29.jpg/480px-Lightning_Pritzerbe_01_%28MK%29.jpg',
     'smoke': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/California_Brush_Fire_day.jpg/480px-California_Brush_Fire_day.jpg',
     'light intensity drizzle rain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Light_rain_on_a_roof.jpg/480px-Light_rain_on_a_roof.jpg',
     'moderate rain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Light_rain_on_a_roof.jpg/480px-Light_rain_on_a_roof.jpg',
     'ragged thunderstorm': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Lightning_Pritzerbe_01_%28MK%29.jpg/480px-Lightning_Pritzerbe_01_%28MK%29.jpg',
     'mist': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/St_James%27_Church%2C_Wetherby_in_the_mist_%288th_November_2020%29.jpg/480px-St_James%27_Church%2C_Wetherby_in_the_mist_%288th_November_2020%29.jpg',
     'proximity shower rain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Rain_shower_after_cold_front_3.JPG/480px-Rain_shower_after_cold_front_3.JPG',
     'haze': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/St_James%27_Church%2C_Wetherby_in_the_mist_%288th_November_2020%29.jpg/480px-St_James%27_Church%2C_Wetherby_in_the_mist_%288th_November_2020%29.jpg',
     'dust': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Car_parking_at_dust_storm_%28Malinovskogo%2C_Rostov%29.jpg/480px-Car_parking_at_dust_storm_%28Malinovskogo%2C_Rostov%29.jpg',
     'thunderstorm with light drizzle': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Lightning_Pritzerbe_01_%28MK%29.jpg/480px-Lightning_Pritzerbe_01_%28MK%29.jpg',
     'proximity sand/dust whirls': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Dust_devil.jpg/480px-Dust_devil.jpg',
     'heavy snow': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Heavy_Snow%2C_London_N14_-_geograph.org.uk_-_2200728.jpg/480px-Heavy_Snow%2C_London_N14_-_geograph.org.uk_-_2200728.jpg',
     'fog': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/St_James%27_Church%2C_Wetherby_in_the_mist_%288th_November_2020%29.jpg/480px-St_James%27_Church%2C_Wetherby_in_the_mist_%288th_November_2020%29.jpg',
     'broken clouds': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Clouds_After_Rain.jpg/480px-Clouds_After_Rain.jpg',
     'tornado': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/F5_tornado_Elie_Manitoba_2007.jpg/480px-F5_tornado_Elie_Manitoba_2007.jpg',
     'thunderstorm': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Lightning_Pritzerbe_01_%28MK%29.jpg/480px-Lightning_Pritzerbe_01_%28MK%29.jpg',
     'light intensity drizzle': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Light_rain_on_a_roof.jpg/480px-Light_rain_on_a_roof.jpg',
     'scattered clouds': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Scattered_clouds.jpg/480px-Scattered_clouds.jpg',
     'thunderstorm with drizzle': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Lightning_Pritzerbe_01_%28MK%29.jpg/480px-Lightning_Pritzerbe_01_%28MK%29.jpg',
     'snow': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Snow_flurries_over_the_pond_%283282132489%29.jpg/480px-Snow_flurries_over_the_pond_%283282132489%29.jpg',
     'heavy intensity shower rain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Heavy_Rain_Approaching_%28152651135%29.jpeg/480px-Heavy_Rain_Approaching_%28152651135%29.jpeg'
}
